### ISSUE TITLE
this.selectBoss is not a function

### ISSUE THREAD

**Issue by Solnse** [netzke/netzke-demo#16]
I don't see anything specifically in the latest commit that would break it, but it worked prior to the commit you made 2 hours ago. "add grid with attachments".

The "Info" panel of Bosses and Clerks no longer populates. "Uncaught TypeError: this.selectBoss is not a function"

![this-selectboss](https://cloud.githubusercontent.com/assets/789870/11871750/6d4db956-a486-11e5-8f81-4b57db2a08c7.gif)

**Comment by mxgrn** [comment]
Thanks for the heads up, that was due to the changes in Core/Basepack API. Fixed with 3b9840c.
